package com.coparently.app.domain.holidays

import org.junit.Test
import java.time.LocalDate
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * The MON-13 holiday tables, held to an independent dataset (the Python `holidays` library).
 *
 * The providers are hand-written computed Kotlin; this test is what makes them verified rather
 * than remembered. For every country and every year in [holidayReference] it compares the full
 * list — dates *and* both names — so a missing day, an extra day, an Easter offset one off, or a
 * renamed holiday all fail with the year and country in the message. The fixture is generated by
 * `tools/generate-holiday-fixture.py`; to change what a provider draws, regenerate it rather than
 * editing either side to match the other.
 */
class HolidayReferenceTest {

    private val providers: Map<String, HolidayProvider> = mapOf(
        "SK" to SlovakHolidays,
        "DE" to GermanHolidays,
        "AT" to AustrianHolidays,
        "RU" to RussianHolidays
    )

    @Test
    fun `the fixture covers every provider this test checks`() {
        assertEquals(providers.keys, holidayReference.keys)
        providers.keys.forEach { code ->
            assertEquals(providers[code], HolidayCountry.fromCode(code).provider, code)
        }
    }

    @Test
    fun `every provider matches the reference data year by year`() {
        providers.forEach { (code, provider) ->
            val expectedByYear = holidayReference.getValue(code)
                .map { (date, nameEn, nameLocal) -> Triple(LocalDate.parse(date), nameEn, nameLocal) }
                .groupBy { it.first.year }

            (HOLIDAY_REFERENCE_FIRST_YEAR..HOLIDAY_REFERENCE_LAST_YEAR).forEach { year ->
                val expected = expectedByYear[year].orEmpty()
                val actual = provider.publicHolidays(year)
                    .map { Triple(it.date, it.nameEn, it.nameLocal) }

                assertEquals(
                    expected,
                    actual,
                    "$code $year differs from holidays v$HOLIDAY_REFERENCE_VERSION"
                )
            }
        }
    }

    @Test
    fun `every holiday carries its provider's language`() {
        providers.values.forEach { provider ->
            provider.publicHolidays(2026).forEach {
                assertEquals(provider.localLanguage, it.localLanguage, it.nameEn)
                assertEquals(false, it.isSchoolVacation, it.nameEn)
            }
        }
    }

    @Test
    fun `Slovakia's consolidation packages are modelled by year`() {
        // The change memory would have got wrong, pinned in words as well as in the fixture:
        // 1 Sep off until 2023, 17 Nov off until 2024, and 8 May / 15 Sep working in 2026 only.
        fun daysOff(year: Int) = SlovakHolidays.publicHolidays(year).map { it.date }.toSet()

        assertTrue(LocalDate.of(2023, 9, 1) in daysOff(2023))
        assertTrue(LocalDate.of(2024, 9, 1) !in daysOff(2024))
        assertTrue(LocalDate.of(2024, 11, 17) in daysOff(2024))
        assertTrue(LocalDate.of(2025, 11, 17) !in daysOff(2025))
        assertTrue(LocalDate.of(2026, 5, 8) !in daysOff(2026))
        assertTrue(LocalDate.of(2026, 9, 15) !in daysOff(2026))
        assertTrue(LocalDate.of(2027, 5, 8) in daysOff(2027))
        assertTrue(LocalDate.of(2027, 9, 15) in daysOff(2027))
    }

    @Test
    fun `Russia draws the statutory days and no decree transfers`() {
        // 2025's decree moved 23 February (a Sunday) to 8 May, and gave 2, 8 May, 13 June,
        // 3 November and 31 December off. None of that is computable, so none of it is drawn.
        val days2025 = RussianHolidays.publicHolidays(2025).map { it.date }.toSet()

        assertEquals(14, days2025.size)
        assertTrue(LocalDate.of(2025, 5, 8) !in days2025)
        assertTrue(LocalDate.of(2025, 12, 31) !in days2025)
        assertTrue(LocalDate.of(2025, 1, 7) in days2025)
    }

    @Test
    fun `a public holiday is found through the shared lookup`() {
        val germanUnity = GermanHolidays.holidayFor(LocalDate.of(2026, 10, 3))

        assertEquals("Tag der Deutschen Einheit", germanUnity?.nameLocal)
        assertEquals(null, GermanHolidays.holidayFor(LocalDate.of(2026, 10, 5)))
    }
}
