package com.coparently.app.domain.holidays

import org.junit.Test
import java.time.LocalDate
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * The MON-13 holiday tables, held to an independent dataset (the Python `holidays` library).
 *
 * The providers are hand-written computed Kotlin; this test is what makes them verified rather
 * than remembered. For every country and every year in [holidayReference] it compares the full
 * list — dates *and* both names — so a missing day, an extra day, an Easter offset one off, or a
 * renamed holiday all fail with the year and country in the message. The fixture is generated by
 * `tools/generate-holiday-fixture.py`; to change what a provider draws, regenerate it rather than
 * editing either side to match the other.
 */
class HolidayReferenceTest {

    private val providers: Map<String, HolidayProvider> = mapOf(
        "SK" to SlovakHolidays,
        "DE" to GermanHolidays,
        "AT" to AustrianHolidays,
        "RU" to RussianHolidays
    )

    @Test
    fun `the fixture covers every provider this test checks`() {
        assertEquals(providers.keys, holidayReference.keys)
        providers.keys.forEach { code ->
            assertEquals(providers[code], HolidayCountry.fromCode(code).provider, code)
        }
    }

    @Test
    fun `every provider matches the reference data year by year`() {
        providers.forEach { (code, provider) ->
            val expectedByYear = holidayReference.getValue(code)
                .map { (date, nameEn, nameLocal) -> Triple(LocalDate.parse(date), nameEn, nameLocal) }
                .groupBy { it.first.year }

            (HOLIDAY_REFERENCE_FIRST_YEAR..HOLIDAY_REFERENCE_LAST_YEAR).forEach { year ->
                val expected = expectedByYear[year].orEmpty()
                val actual = provider.publicHolidays(year)
                    .map { Triple(it.date, it.nameEn, it.nameLocal) }

                assertEquals(
                    expected,
                    actual,
                    "$code $year differs from holidays v$HOLIDAY_REFERENCE_VERSION"
                )
            }
        }
    }

    @Test
    fun `the regional fixture covers exactly the regions whose public holidays differ`() {
        // A Land the app offers with no fixture would be drawn unverified; a fixture key the
        // app does not offer would be a region nobody can pick. Slovakia's kraje are regions for
        // the school calendar only - the library has no Slovak subdivision - so they are held to
        // the nationwide list by the next-but-one test instead.
        val offered = HolidayCountry.entries
            .filter { it != HolidayCountry.SLOVAKIA }
            .flatMap { country -> country.regions.map { "${country.code}-$it" } }
            .toSet()

        assertEquals(offered, holidayRegionReference.keys)
    }

    @Test
    fun `every region matches the reference data year by year`() {
        // The fixture lists only what a region adds, so the expected list is the nationwide one
        // plus those days — which also proves a regional calendar never *drops* a nationwide day.
        holidayRegionReference.forEach { (key, added) ->
            val countryCode = key.substringBefore('-')
            val regionCode = key.substringAfter('-')
            val provider = HolidayLocation.of(countryCode, regionCode).provider!!
            val expectedByYear = (holidayReference.getValue(countryCode) + added)
                .map { (date, nameEn, nameLocal) -> Triple(LocalDate.parse(date), nameEn, nameLocal) }
                .groupBy { it.first.year }

            (HOLIDAY_REFERENCE_FIRST_YEAR..HOLIDAY_REFERENCE_LAST_YEAR).forEach { year ->
                val expected = expectedByYear[year].orEmpty().sortedBy { it.first }
                val actual = provider.publicHolidays(year)
                    .map { Triple(it.date, it.nameEn, it.nameLocal) }

                assertEquals(expected, actual, "$key $year differs from holidays v$HOLIDAY_REFERENCE_VERSION")
            }
        }
    }

    @Test
    fun `a Slovak kraj draws exactly the nationwide public holidays`() {
        // Act 241/1993 is national: a kraj adds its spring holidays (SchoolVacationReferenceTest)
        // and nothing else, so its public holidays are the nationwide fixture's, every year.
        assertEquals(8, SlovakHolidays.regions.size)
        SlovakHolidays.regions.forEach { region ->
            val kraj = HolidayLocation.of("SK", region).provider!!
            (HOLIDAY_REFERENCE_FIRST_YEAR..HOLIDAY_REFERENCE_LAST_YEAR).forEach { year ->
                assertEquals(SlovakHolidays.publicHolidays(year), kraj.publicHolidays(year), "SK-$region $year")
            }
        }
    }

    @Test
    fun `every region adds something to the nationwide calendar`() {
        // A region that added nothing would be a picker row that promises a feature.
        GermanHolidays.regions.forEach { region ->
            val regional = GermanHolidays.forRegion(region).publicHolidays(2026)
            assertTrue(regional.size > GermanHolidays.publicHolidays(2026).size, region)
        }
    }

    @Test
    fun `Bavaria gets its own days and Berlin does not get them`() {
        // The case the state setting exists for, pinned in words as well as in the fixture.
        fun daysOff(region: String) =
            GermanHolidays.forRegion(region).publicHolidays(2026).map { it.date }.toSet()

        assertTrue(LocalDate.of(2026, 1, 6) in daysOff("BY"))
        assertTrue(LocalDate.of(2026, 6, 4) in daysOff("BY"))
        assertTrue(LocalDate.of(2026, 1, 6) !in daysOff("BE"))
        assertTrue(LocalDate.of(2026, 3, 8) in daysOff("BE"))
        // Assumption Day in Bavaria is a Catholic-municipality holiday and deliberately absent.
        assertTrue(LocalDate.of(2026, 8, 15) !in daysOff("BY"))
        assertTrue(LocalDate.of(2026, 8, 15) in daysOff("SL"))
    }

    @Test
    fun `an unknown or missing region draws the nationwide days`() {
        // A newer build's region read by an older one must not blank the calendar.
        assertEquals(GermanHolidays, GermanHolidays.forRegion(null))
        assertEquals(GermanHolidays, GermanHolidays.forRegion("XX"))
        assertEquals(GermanHolidays, GermanHolidays.forRegion("Augsburg"))
    }

    @Test
    fun `every holiday carries its provider's language`() {
        providers.values.forEach { provider ->
            provider.publicHolidays(2026).forEach {
                assertEquals(provider.localLanguage, it.localLanguage, it.nameEn)
                assertEquals(false, it.isSchoolVacation, it.nameEn)
            }
        }
    }

    @Test
    fun `Slovakia's consolidation packages are modelled by year`() {
        // The change memory would have got wrong, pinned in words as well as in the fixture:
        // 1 Sep off until 2023, 17 Nov off until 2024, and 8 May / 15 Sep working in 2026 only.
        fun daysOff(year: Int) = SlovakHolidays.publicHolidays(year).map { it.date }.toSet()

        assertTrue(LocalDate.of(2023, 9, 1) in daysOff(2023))
        assertTrue(LocalDate.of(2024, 9, 1) !in daysOff(2024))
        assertTrue(LocalDate.of(2024, 11, 17) in daysOff(2024))
        assertTrue(LocalDate.of(2025, 11, 17) !in daysOff(2025))
        assertTrue(LocalDate.of(2026, 5, 8) !in daysOff(2026))
        assertTrue(LocalDate.of(2026, 9, 15) !in daysOff(2026))
        assertTrue(LocalDate.of(2027, 5, 8) in daysOff(2027))
        assertTrue(LocalDate.of(2027, 9, 15) in daysOff(2027))
    }

    @Test
    fun `Russia draws the statutory days and no decree transfers`() {
        // 2025's decree moved 23 February (a Sunday) to 8 May, and gave 2, 8 May, 13 June,
        // 3 November and 31 December off. None of that is computable, so none of it is drawn.
        val days2025 = RussianHolidays.publicHolidays(2025).map { it.date }.toSet()

        assertEquals(14, days2025.size)
        assertTrue(LocalDate.of(2025, 5, 8) !in days2025)
        assertTrue(LocalDate.of(2025, 12, 31) !in days2025)
        assertTrue(LocalDate.of(2025, 1, 7) in days2025)
    }

    @Test
    fun `a public holiday is found through the shared lookup`() {
        val germanUnity = GermanHolidays.holidayFor(LocalDate.of(2026, 10, 3))

        assertEquals("Tag der Deutschen Einheit", germanUnity?.nameLocal)
        assertEquals(null, GermanHolidays.holidayFor(LocalDate.of(2026, 10, 5)))
    }
}
