package com.coparently.app.domain.holidays

import org.junit.Test
import java.time.LocalDate
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/** One expected school vacation in [schoolVacationReference], dates as ISO strings. */
internal data class ReferenceVacation(
    val first: String,
    val last: String,
    val nameEn: String,
    val nameLocal: String
)

/**
 * The MON-13 school-vacation tables outside Czechia, held to the OpenHolidays dataset.
 *
 * Slovakia's, Austria's and each German Land's vacations are dated tables, not computations, so
 * this test is what makes them sourced rather than typed: for every calendar the fixture names it
 * compares the full list of periods — first day, last day and both names — with what the provider
 * returns. The fixture is generated by `tools/generate-school-vacation-fixture.py` from a pinned
 * commit of the dataset; to change a table, regenerate the fixture and read the diff, never edit
 * both sides to agree.
 */
class SchoolVacationReferenceTest {

    /** Every calendar the fixture covers, by the key the script writes. */
    private fun calendarFor(key: String): HolidayProvider {
        val country = key.substringBefore('-')
        val region = key.substringAfter('-', missingDelimiterValue = "").ifEmpty { null }
        val location = HolidayLocation.of(country, region)
        assertEquals(region, location.regionCode, "$key names a region the app does not offer")
        return location.provider!!
    }

    /** All periods a provider returns, across every year the fixture can touch, in date order. */
    private fun periodsOf(provider: HolidayProvider): List<ReferenceVacation> {
        val years = schoolVacationReference.values.flatten()
            .flatMap { listOf(LocalDate.parse(it.first).year, LocalDate.parse(it.last).year) }
        return ((years.min() - 1)..(years.max() + 1))
            .flatMap { provider.schoolVacations(it) }
            .distinct()
            .map { (range, names) ->
                ReferenceVacation(
                    range.start.toString(),
                    range.endInclusive.toString(),
                    names.first,
                    names.second
                )
            }
            .sortedBy { it.first }
    }

    @Test
    fun `the fixture covers exactly the calendars that draw these tables`() {
        // Slovakia and Austria nationwide, every Slovak kraj and every German Land. A region the
        // app offers with no fixture would be drawn unverified; a key the app cannot select would
        // be dead data.
        val expected = setOf("SK", "AT") +
            SlovakHolidays.regions.map { "SK-$it" } +
            GermanHolidays.regions.map { "DE-$it" }

        assertEquals(expected, schoolVacationReference.keys)
    }

    @Test
    fun `every calendar matches the reference data period by period`() {
        schoolVacationReference.forEach { (key, expected) ->
            assertEquals(
                expected,
                periodsOf(calendarFor(key)),
                "$key differs from openholidaysapi.data@$SCHOOL_VACATION_REFERENCE_COMMIT"
            )
        }
    }

    @Test
    fun `nothing before school year 2025-26 is drawn`() {
        // The tables start where the sourced data starts; an earlier date would be unsourced.
        val firstDay = LocalDate.parse(SCHOOL_VACATION_REFERENCE_FIRST_DAY)
        schoolVacationReference.keys.forEach { key ->
            periodsOf(calendarFor(key)).forEach {
                assertFalse(LocalDate.parse(it.first).isBefore(firstDay), "$key ${it.first}")
            }
        }
    }

    @Test
    fun `Germany without a Land draws no school vacations`() {
        // German school holidays are Land law; there is no nationwide period to fall back on.
        (2025..2031).forEach { assertTrue(GermanHolidays.schoolVacations(it).isEmpty(), "$it") }
    }

    @Test
    fun `Bavaria's school calendar is its own`() {
        // Pinned in words as well as in the fixture: the checked 2025/26 sample.
        val bavaria = GermanHolidays.forRegion("BY")
        val berlin = GermanHolidays.forRegion("BE")

        assertEquals("Herbstferien", bavaria.holidayFor(LocalDate.of(2025, 11, 5))?.nameLocal)
        assertEquals("Buß- und Bettag", bavaria.holidayFor(LocalDate.of(2025, 11, 19))?.nameLocal)
        assertEquals("Sommerferien", bavaria.holidayFor(LocalDate.of(2026, 9, 14))?.nameLocal)
        assertEquals(null, berlin.holidayFor(LocalDate.of(2026, 9, 14)))
    }

    @Test
    fun `a public holiday inside a vacation is still the public holiday`() {
        // The precedence `HolidayProvider.holidayFor` documents, across the new tables.
        val christmas = LocalDate.of(2025, 12, 25)
        listOf(GermanHolidays.forRegion("BY"), AustrianHolidays, SlovakHolidays).forEach { provider ->
            val holiday = provider.holidayFor(christmas)
            assertEquals(false, holiday?.isSchoolVacation, provider.localLanguage)
        }
        val dayBeforeChristmasEve = LocalDate.of(2025, 12, 23)
        assertEquals(true, SlovakHolidays.holidayFor(dayBeforeChristmasEve)?.isSchoolVacation)
        assertEquals("sk", SlovakHolidays.holidayFor(dayBeforeChristmasEve)?.localLanguage)
    }

    @Test
    fun `a kraj draws its own spring week and no other kraj's`() {
        // The three groups the ministry staggers the spring holidays across, 2025/26.
        val bratislava = SlovakHolidays.forRegion("BL")
        val zilina = SlovakHolidays.forRegion("ZI")
        val kosice = SlovakHolidays.forRegion("KI")
        val westWeek = LocalDate.of(2026, 2, 18)
        val eastWeek = LocalDate.of(2026, 3, 4)

        assertEquals("Jarné prázdniny", bratislava.holidayFor(westWeek)?.nameLocal)
        assertEquals("sk", bratislava.holidayFor(westWeek)?.localLanguage)
        assertEquals(true, bratislava.holidayFor(westWeek)?.isSchoolVacation)
        assertEquals(null, zilina.holidayFor(westWeek))
        assertEquals(null, kosice.holidayFor(westWeek))
        assertEquals("Jarné prázdniny", kosice.holidayFor(eastWeek)?.nameLocal)
        assertEquals(null, bratislava.holidayFor(eastWeek))
        assertEquals("Spring vacation", zilina.holidayFor(LocalDate.of(2026, 2, 25))?.nameEn)
    }

    @Test
    fun `a kraj keeps every nationwide period`() {
        // A region adds; it never replaces. The fixture proves it period by period too.
        val nationwide = (2025..2028).flatMap { SlovakHolidays.schoolVacations(it) }.toSet()
        SlovakHolidays.regions.forEach { region ->
            val kraj = (2025..2028).flatMap { SlovakHolidays.forRegion(region).schoolVacations(it) }.toSet()
            assertTrue(kraj.containsAll(nationwide), region)
            assertEquals(3, (kraj - nationwide).size, "$region: one spring week per school year")
        }
    }

    @Test
    fun `an unknown or missing kraj draws the nationwide calendar`() {
        // A newer build's region read by an older one, or a German code left behind by a move.
        assertEquals(SlovakHolidays, SlovakHolidays.forRegion(null))
        assertEquals(SlovakHolidays, SlovakHolidays.forRegion("BY"))
        assertEquals(SlovakRegion.NI, SlovakRegion.fromCode(" ni "))
    }

    @Test
    fun `regional breaks are not drawn where no region is chosen or modelled`() {
        // Slovakia's spring holidays (by kraj) are drawn only with a kraj, and Austria's
        // semester and summer breaks (by Land) are left out rather than drawn for the wrong Land.
        assertEquals(null, SlovakHolidays.holidayFor(LocalDate.of(2026, 2, 18)))
        assertEquals(null, SlovakHolidays.holidayFor(LocalDate.of(2026, 3, 4)))
        assertEquals(null, AustrianHolidays.holidayFor(LocalDate.of(2026, 2, 4)))
        assertEquals(null, AustrianHolidays.holidayFor(LocalDate.of(2026, 7, 20)))
        assertTrue(AustrianHolidays.regions.isEmpty())
    }
}
