package com.coparently.app.presentation.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color

// Generated by tools/generate-contrast-schemes.py from the standard schemes in Theme.kt.
// Do not edit by hand: change the standard scheme, or the script, and regenerate.
// ContrastSchemesTest holds every target the script aims for.

/**
 * The light scheme at medium contrast: foregrounds moved to Material's
 * medium-contrast targets, backgrounds unchanged.
 */
internal val LightMediumContrastColorScheme: ColorScheme = LightColorScheme.copy(
    primary = Color(0xFF1629C2),
    secondary = Color(0xFF404256),
    tertiary = Color(0xFF014D37),
    onSurfaceVariant = Color(0xFF43424B),
    error = Color(0xFF8C000B),
    outline = Color(0xFF5F5E68),
    outlineVariant = Color(0xFF7C7984)
)

/**
 * The light scheme at high contrast: foregrounds moved to Material's
 * high-contrast targets, backgrounds unchanged.
 */
internal val LightHighContrastColorScheme: ColorScheme = LightColorScheme.copy(
    primary = Color(0xFF1629C2),
    secondary = Color(0xFF404256),
    tertiary = Color(0xFF014D37),
    onBackground = Color(0xFF000000),
    onSurface = Color(0xFF000000),
    onSurfaceVariant = Color(0xFF24232C),
    error = Color(0xFF8C000B),
    outline = Color(0xFF43424B),
    outlineVariant = Color(0xFF605E67),
    inverseOnSurface = Color(0xFFFFFFFF)
)

/**
 * The dark scheme at medium contrast: foregrounds moved to Material's
 * medium-contrast targets, backgrounds unchanged.
 */
internal val DarkMediumContrastColorScheme: ColorScheme = DarkColorScheme.copy(
    primary = Color(0xFFDFDDFF),
    secondary = Color(0xFFDFDEF7),
    onSecondary = Color(0xFF26273A),
    tertiary = Color(0xFF7EF7C6),
    onTertiary = Color(0xFF00301F),
    onBackground = Color(0xFFFFFFFF),
    onSurface = Color(0xFFFFFFFF),
    onSurfaceVariant = Color(0xFFE2DFEA),
    error = Color(0xFFFFD8D2),
    onError = Color(0xFF5B0000),
    outline = Color(0xFFB6B4BF),
    outlineVariant = Color(0xFF94939D),
    inversePrimary = Color(0xFF433EDC)
)

/**
 * The dark scheme at high contrast: foregrounds moved to Material's
 * high-contrast targets, backgrounds unchanged.
 */
internal val DarkHighContrastColorScheme: ColorScheme = DarkColorScheme.copy(
    primary = Color(0xFFDFDDFF),
    onPrimary = Color(0xFF000000),
    onPrimaryContainer = Color(0xFFFFFFFF),
    secondary = Color(0xFFDFDEF7),
    onSecondary = Color(0xFF000000),
    onSecondaryContainer = Color(0xFFFFFFFF),
    tertiary = Color(0xFF7EF7C6),
    onTertiary = Color(0xFF000000),
    onTertiaryContainer = Color(0xFFFFFFFF),
    onBackground = Color(0xFFFFFFFF),
    onSurface = Color(0xFFFFFFFF),
    onSurfaceVariant = Color(0xFFFFFFFF),
    error = Color(0xFFFFD8D2),
    onError = Color(0xFF000000),
    onErrorContainer = Color(0xFFFFFFFF),
    outline = Color(0xFFE1DFEB),
    outlineVariant = Color(0xFFB6B4BF),
    inverseOnSurface = Color(0xFF000000),
    inversePrimary = Color(0xFF433EDC)
)
