package com.coparently.app.wire

import java.io.File

/**
 * One wire fixture file.
 *
 * The file is a JSON object with `about` (one sentence: who writes this shape and why it is
 * here), `document` (the Firestore document), `reads` (what this build must read from it — see
 * [WireContract.read] — or null when it must skip it, with `skipped` saying why) and optionally
 * `notPreserved` (dotted paths a read-then-write loses, each with the reason).
 *
 * @property file The file, for messages.
 * @property collection The directory it sits in, which names its [WireContract].
 * @property current True for `wire/current/`: what *this* build writes, regenerated rather than
 *   hand-written, and read by the previous build in CI.
 */
data class WireFixture(
    val file: File,
    val collection: String,
    val current: Boolean,
    val about: String,
    val document: Map<String, Any?>,
    val reads: Map<String, Any?>?,
    val skipped: String?,
    val notPreserved: Map<String, String>
) {
    /** `current/events/repository-save` or `events/older-build`, for test names. */
    val name: String
        get() = (if (current) "current/" else "") + "$collection/${file.nameWithoutExtension}"

    override fun toString(): String = name
}

/**
 * Where the wire fixtures live, and how they are read.
 *
 * `app/src/test/resources/wire/<collection>/<case>.json` holds documents *other* builds write —
 * older ones with keys missing, newer ones with keys and codec versions this build does not know —
 * written by hand. `wire/current/<collection>/<case>.json` holds what *this* build writes,
 * regenerated by `CurrentWireFixturesTest`. Read from the source tree, not the classpath, so that
 * test can rewrite them and the CI step that runs the previous build's `WireContractTest` over
 * this build's `current/` only has to copy a directory.
 */
internal object WireFixtures {

    /** The environment variable that makes `CurrentWireFixturesTest` rewrite `wire/current/`. */
    const val UPDATE_ENV = "UPDATE_WIRE_FIXTURES"

    /** The fixture root: Gradle runs unit tests in the module directory, an IDE may use the root. */
    val root: File by lazy {
        listOf(File("src/test/resources/wire"), File("app/src/test/resources/wire"))
            .firstOrNull { it.isDirectory }
            ?: error("No wire fixture directory under ${File("").absolutePath}")
    }

    /** `wire/current/`. */
    val currentRoot: File get() = File(root, "current")

    /** Every fixture, hand-written and current, sorted by name. */
    fun all(): List<WireFixture> {
        val handWritten = root.listFiles().orEmpty()
            .filter { it.isDirectory && it.name != "current" }
            .flatMap { dir -> jsonFiles(dir).map { load(it, dir.name, current = false) } }
        val current = currentRoot.listFiles().orEmpty()
            .filter { it.isDirectory }
            .flatMap { dir -> jsonFiles(dir).map { load(it, dir.name, current = true) } }
        return (handWritten + current).sortedBy { it.name }
    }

    /** One fixture file, parsed. */
    @Suppress("UNCHECKED_CAST")
    fun load(file: File, collection: String, current: Boolean): WireFixture {
        val json = WireJson.parse(file.readText()) as? Map<String, Any?>
            ?: error("$file is not a JSON object")
        return WireFixture(
            file = file,
            collection = collection,
            current = current,
            about = json["about"] as? String ?: error("$file has no \"about\""),
            document = json["document"] as? Map<String, Any?> ?: error("$file has no \"document\" object"),
            reads = json["reads"] as? Map<String, Any?>,
            skipped = json["skipped"] as? String,
            notPreserved = (json["notPreserved"] as? Map<String, Any?>).orEmpty()
                .mapValues { (_, reason) -> reason.toString() }
        )
    }

    /** The JSON object a current fixture file holds for [write], as `CurrentWireFixturesTest` writes it. */
    fun currentJson(write: CurrentWrite, reads: Map<String, Any?>?): Map<String, Any?> = buildMap {
        put("about", write.about)
        put("document", write.document)
        put("reads", reads)
        if (write.olderBuildsMayDrop.isNotEmpty()) put("notPreserved", write.olderBuildsMayDrop)
    }

    private fun jsonFiles(dir: File): List<File> =
        dir.listFiles().orEmpty().filter { it.isFile && it.extension == "json" }
}
